# Generated by Django 5.0.9 on 2024-10-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=25)),
                ("price", models.FloatField()),
                ("qty", models.IntegerField()),
            ],
        ),
    ]
