# Generated by Django 5.0.9 on 2024-11-11 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="student_data",
            fields=[
                ("admissions_date", models.DateField(auto_created=True)),
                ("roll", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=254)),
                ("create_record", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
