# Generated by Django 5.0.9 on 2024-11-12 06:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("curdapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student_data",
            name="admissions_date",
            field=models.DateField(),
        ),
    ]
