# Generated by Django 5.0.9 on 2024-11-12 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="employee_data",
            fields=[
                ("emp_id", models.IntegerField(primary_key=True, serialize=False)),
                ("emp_name", models.CharField(max_length=30)),
                ("emp_sal", models.IntegerField()),
                ("emp_city", models.CharField(max_length=30)),
            ],
        ),
    ]
