# Generated by Django 5.0.9 on 2024-10-30 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("modelapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="model_feedback_form",
            new_name="model_form",
        ),
    ]
